<?php
session_start();
// Purpose: Set up the Help page
require_once 'login.php';
echo<<<_HEAD1
<html>
<body>
<link rel="stylesheet" href=style.css>
_HEAD1;
include 'menuf.php';
echo<<<_BODY1
<div class="content">
<div class="sub_box">
<center><h1> Website Help Page: a User Guide</h1></center>
</div>
<p>This website hosts a suite of tools for analyzing a user selected protein family. </p>

<!-- Navigation Menu -->
<nav>
<p>Navigate to:</p>
<div class='vert_line_s'>
<ul>
        <li><a href="#use">Website Use</a></li>
        <li><a href="#func">Functionality</a></li>
</ul>
</div>
</nav>

<hr></hr>
<h2 id='use'>How to Use this Website</h2>

<p>The home page is the data selection page. Here, users have the option to search for a specific protein from a specific taxonomic group, select a previous search, or use the example dataset, Glucose-6-Phosphatase Proteins from Aves. The user can submit a more <a href="https://bioinfmsc8.bio.ed.ac.uk/~s2901468/iwd2_website/about.php">stringent search or a less stringent search</a>, as desired.</p>

<p><b>Data Selection Options:</b></p>
<ol>
        <li>Select taxonomic group and protein</li>
        <li>Use a previous search</li>
        <li>Example Data: Glucose-6-Phosphatase Proteins from Aves</li>
</ol>

<p>Once a selection has been made, the tools are populated with this data. Users can browse through the different functions as listed above for their selected data.</p>
<p><b>Note:</b> If a selection has not been made, attempting to access the functionality pages (Conservation Analysis, MSA, Phylogenetic Analysis, Data Download) will redirect the user back to the home page.</p>
<hr></hr>
<h2 id='func'>Functionality</h2>
<div id="div1"
<p>The following functions are hosted on this website:</p>
<p>1. <a href="https://bioinfmsc8.bio.ed.ac.uk/~s2901468/iwd2_website/a1.php">Protein conservation analysis</a></p>
<ul>
	<li>This tool allows users to visualize conservation of amino acid residues at each position in a specified protein across the set of input protein sequences</li>
	<li>The conservation plot is generated via plotcon, which calculates sequence conservation across windows in the Multiple Sequence Alignment. The resulting visual represents the average postion similarity across each window.</li>
	<li>Note: In plotcon, position similarity is an average over all pairwise substitution scores at a given position.</li>
	<li>Users can change the window size over which sequence conservation is calculated. Larger window sizes produce smoother conservation plots, which can be appropriate for longer sequences or if the plot is very noisy. The default window size is 4.</li> 
</ul>
<p>2. <a href="https://bioinfmsc8.bio.ed.ac.uk/~s2901468/iwd2_website/a2.php">Multiple Sequence Alignment</a></p>
<ul>
	<li>The <b>Multiple Sequence Alignment (MSA)</b> visualizes the alignment of multiple (>2) sequences, identifying regions of sequence similarity between them (Zhang et al., 2024). MSA is the basis for most analyses hosted on this website.</li>
	<li>The MSA and consensus sequence generated from CLUSTALO for the set of inputted protein sequences are visualized on this page.</li>
		<li>The <b>consensus sequence</b> is a single sequence that represents a MSA. The consensus sequence is generated by identifying the plurality amino acid residue at each position. This sequence is treated as the reference sequence in the MSA display.</li>
		<li><u>Options:</u></li>
		<ul>
			<li><b>All:</b> Shows amino acids at all positions.</li>
			<li><b>Identities:</b> Shows only strong matches, the amino acid in the consensus sequence.</li>
			<li><b>Non-Identities:</b> Identical matches to the consensus (identical matches) are represented as '.', but similar matches displayed as lowercase letter codes (e.g., a).</li>
			<li><b>Similarities:</b> Only amino acids that are chemically similar are displayed, in lowercase. Identical residues are represented as '.'.</li>
			<li><b>Dissimilarities:</b> Only amino acids that are different from the consensus sequence are displayed. Identical and similar residues are represented as '.'</li>
		</ul>
		<li><u>Symbols:</u></li>
		<ul>
			<li><i>Matches (Identities)</i> are represented by the uppercase protein letter code (e.g., A).</li>
			<li><i>Chemically similar residues</i> are represented by lowercase protein letter codes (e.g., a).</li>
			<li>Amino acids at positions with very <i>weak similarity</i> are represented by dots (.).</li> 
			<li><i>Gaps</i> are represented by dashes (-).</li>
			<li>In the <u>consensus sequence</u>, lowercase protein letter codes (e.g., a) represent <i>weak matches</i>.</li>
			<li>In the <u>consensus sequence</u>, 'x' represents positions with no strong consensus.</li> 
		</ul>
		<li>See <a target="_blank" rel="noopener noreferrer" href="https://www.bioinformatics.nl/cgi-bin/emboss/help/showalign">EMBOSS showalign</a> documentation for more detailed information.</li>
	<li>The MSA can be downloaded as a multi-line MSA FASTA file, for any additional external analyses.</li>
	<li>Several statistics can be viewed for the MSA:</li>
<ul>
		<li>Amino Acid Substitutions - Heatmap</li>
		<li>Sequence Lengths - Input Protein Sequence lengths across the input sequences. The average, minimum, maximum, and associated IDs are printed, so users can examine different aspects about the similarity of this protein sequence across a given family of organisms.</li>
		<li>Gap Distribution - Another approach for characterizing the MSA is identifying the number and gap composition across aligned sequences. A histogram of gap composition across protein sequences is displayed here. Additionally, the average, minimum, and maximum gap composition with associated sequence IDs are printed.</li>
</ul>
</ul>
<p>3. <a href="https://bioinfmsc8.bio.ed.ac.uk/~s2901468/iwd2_website/a3.php">Motif Analysis</a></p>
<ul>
	<li><b>PROSITE motifs</b> are biologically meaningful patterns characteristic of different protein families or domains (Sigrist, 2002).</li>
	<li>The requested input protein sequences are scanned for motifs from PROSITE.</li>
	<li>If a sequence contains a PROSITE motifs, details regarding the motif are reported along with the sequence ID.</li>
	<li>A pie chart displays a summary of the PROSITE content across the input protein sequences</li>
</ul>
<p>4. <a href="https://bioinfmsc8.bio.ed.ac.uk/~s2901468/iwd2_website/a4.php">Phylogenetic Analysis</a></p>
<ul>
	<li>The output is a phylogenetic tree that evaluates the sequence similarity of the input protein sequences and infers evolutionary relationships between them.</li>
	<li>The substitution matrix used in generating the tree is <a target="_blank" rel="noopener noreferrer" href="https://www.pnas.org/doi/epdf/10.1073/pnas.89.22.10915">BLOSUM62</a>, which is a commonly used substitution matrix (the default substitution matrix in BLASTP)</li>
	<li>Note: since implementation is server-side, this may take a little while to run.</li>
</ul>
<p>5. <a href="https://bioinfmsc8.bio.ed.ac.uk/~s2901468/iwd2_website/fasta.php">Data Download</a></p>
<ul>
	<li>This page allows users to examine the data by organism, sequence ID, and the sequence itself.</li>
	<li>The requested input data can be downloaded as a multi-line FASTA file from this page, allowing any external analyses</li>
</ul>
</body>
</html>
</div>
</div>
_BODY1;
?>
